version: "3"
services:
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    restart: unless-stopped
    env_file:
      - .env
#    ports:
#      - "4317:4317"
#      - "4444:4444"
    networks:
      - my_network
#    deploy:
#      resources:
#        limits:
#          cpus: "4.0"
#          memory: "4g"


  mongodb:
    image: mongo:latest
    container_name: mongodb
#    ports:
#      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - local_network

  redis:
    image: redis
    container_name: redis
    volumes:
      - redis_data:/data
#    ports:
#      - "6379:6379"
    networks:
      - local_network

  app:
    build: .
    restart: on-failure
    depends_on:
      - selenium
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - "./:/app"
    networks:
      - my_network
      - local_network
    command: sh -c "python3 /app/wait_for_selenium.py && uvicorn manager:app --reload --host 0.0.0.0"

  celery-worker:
    build: .
    container_name: celery-worker
    depends_on:
      - redis
      - app
    networks:
      - my_network
      - local_network
    command: celery -A settings.tasks worker --loglevel=info


networks:
  my_network:
    driver: bridge

  local_network:
    internal: true